<?php

namespace ICanBoogie;

/**
 * @var $view \ICanBoogie\View\View
 * @var $content string
 * @var $page_title string
 */

?><!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title><?= $page_title ?> – ICanBoogie</title>

	<link rel="stylesheet" type="text/css" href="/assets/page.css" />
</head>
<body>

<?= $content ?>

</body>
</html>
