<?php

namespace ICanBoogie;

/**
 * @var $content string
 */

?><div class="hero-title">
	<div class="content">
		<h1><img src="/assets/icanboogie.svg" alt="ICanBoogie" /></h1>

		<ul class="links">
			<li><a href="https://icanboogie.org/docs/4.0/icanboogie">Introduction</a></li>
			<li><a href="https://icanboogie.org/docs">Documentation</a></li>
			<li><a href="https://github.com/icanboogie">GitHub</a></li>
			<li><a href="https://icanboogie.org">News</a></li>
		</ul>

		<p><?= escape($content) ?></p>
	</div>
</div>
