<?php

namespace ICanBoogie;

/**
 * @var $content string
 */

?><div class="flex-center full-height">
	<div class="content">
		<h1><img src="/assets/icanboogie.svg" alt="ICanBoogie" /></h1>

		<ul class="links">
			<li><a href="http://icanboogie.org">Documentation</a></li>
			<li><a href="http://api.icanboogie.org">API</a></li>
			<li><a href="https://github.com/icanboogie/icanboogie#readme">README</a></li>
			<li><a href="https://github.com/icanboogie">GitHub</a></li>
		</ul>

		<p><?= escape($content) ?></p>
	</div>
</div>
